builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-w -s -X github.com/SAP/jenkins-library/cmd.GitCommit={{ .Env.GITHUB_SHA }}"
      - "-X github.com/SAP/jenkins-library/pkg/log.LibraryRepository={{ .Env.GITHUB_REPOSITORY }}"
      - "-X github.com/SAP/jenkins-library/pkg/telemetry.LibraryRepository=https://github.com/{{ .Env.GITHUB_REPOSITORY }}.git"

    ignore:
      - goarch: 386
      - goos: windows
        goarch: arm
      - goos: linux
        goarch: arm

    no_unique_dist_dir: true

    binary: "piper_master-{{ .Os }}.{{ replace .Arch \"amd64\" \"x86_64\" }}"

project_name: Piper

release:
  github:
    owner: inf2381
    name: jenkins-library

  ids:
  - None

  name_template: "v{{.Version}}"

  extra_files:
    - glob: dist/**/piper_*
