builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-w -s -X github.com/SAP/jenkins-library/cmd.GitCommit={{ .Env.GITHUB_SHA }}"
      - "-X github.com/SAP/jenkins-library/pkg/log.LibraryRepository={{ .Env.GITHUB_REPOSITORY }}"
      - "-X github.com/SAP/jenkins-library/pkg/telemetry.LibraryRepository=https://github.com/{{ .Env.GITHUB_REPOSITORY }}.git"

    binary: "piper_{{ .Os }}_{{ .Arch }}"

project_name: Piper

release:
  github:
    owner: SAP
    name: https://github.com/SAP/jenkins-library.git

  name_template: "v{{.Version}}"

brews:
  - homepage: 'https://github.com/inf2381/jenkins-library'
    description: 'Shared library for Continuous Delivery pipelines.'
    folder: Formula
    commit_author:
      name: inf2381
      email: marc.bormeth@sap.com
    tap:
      owner: Marc Bormeth
      name: PiperTest
